# Generated by Django 5.1.7 on 2025-05-01 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.TextField()),
                ('tipo_entidad', models.TextField()),
                ('direccion_fiscal', models.TextField(unique=True)),
                ('telefono_entidad', models.TextField(unique=True)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('sitio_web', models.URLField(blank=True, null=True, unique=True)),
                ('sector_economico', models.TextField()),
                ('nombre_responsable', models.TextField(unique=True)),
                ('cargo_puesto', models.TextField()),
                ('tipo_documento_identidad', models.TextField()),
                ('numero_documento', models.TextField()),
                ('email_responsable', models.EmailField(max_length=254, unique=True)),
                ('telefono_responsable', models.TextField(unique=True)),
                ('direccion_responsable', models.TextField(unique=True)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
