# Generated by Django 5.1.7 on 2025-03-31 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(unique=True)),
                ('private_key', models.TextField(unique=True)),
                ('entidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.entidad')),
            ],
        ),
    ]
