# Generated by Django 5.1.7 on 2025-04-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_credencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencial',
            name='tipo_sistema',
            field=models.TextField(null=True),
        ),
    ]
