# Generated by Django 5.1.7 on 2025-04-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_credencial_tipo_sistema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credencial',
        ),
    ]
