# Generated by Django 5.1.7 on 2025-04-02 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0004_delete_credencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(unique=True)),
                ('tipo_sistema', models.TextField(null=True)),
                ('public_key', models.TextField(unique=True)),
                ('private_key', models.TextField(unique=True)),
                ('ntw_sec_pub', models.TextField(blank=True, null=True)),
                ('entidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.entidad')),
            ],
        ),
    ]
