# Generated by Django 5.1.7 on 2025-04-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencial',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
